<script setup>
    const smoothieKingIngredients = new Map([
  ['Almond Butter', 'Protein'],
  ['Almonds', 'Protein'],
  ['Apple Blueberry Juice Blend', 'Fruits and Veggies'],
  ['Apple Juice Blend', 'Fruits and Veggies'],
  ['Apple Pineapple Juice Blend', 'Fruits and Veggies'],
  ['Bananas', 'Fruits and Veggies'],
  ['Blueberries', 'Fruits and Veggies'],
  ['Carrots', 'Fruits and Veggies'],
  ['Cold Brew Coffee', 'Energy'],
  ['Dairy Whey Blend', 'Protein'],
  ['Dates', 'Fruits and Veggies'],
  ['Diet Down Enhancer', 'Enhancers'],
  ['Electrolyte Blend', 'Energy'],
  ['Energy Boost Enhancer', 'Energy'],
  ['Espresso', 'Energy'],
  ['Fiber Blend Enhancer', 'Enhancers'],
  ['FITAID + Paleo Protein Enhancer', 'Energy'],
  ['Ginger', 'Fruits and Veggies'],
  ['Gladiator Protein Chocolate', 'Protein'],
  ['Gladiator Protein Strawberry', 'Protein'],
  ['Gladiator Protein Vanilla', 'Protein'],
  ['Greek Nonfat Yogurt', 'Protein'],
  ['Gut Health Enhancer', 'Enhancers'],
  ['Hulk Blend', 'Fruits and Veggies'],
  ['Immune Support Enhancer', 'Enhancers'],
  ['Joint Health Enhancer with Collagen', 'Enhancers'],
  ['Kale', 'Fruits and Veggies'],
  ['Keto Protein Blend', 'Fruits and Veggies'],
  ['Kiwi Apple Juice Blend', 'Fruits and Veggies'],
  ['Lean1 Chocolate Protein', 'Protein'],
  ['Lean1 Vanilla Protein', 'Protein'],
  ['Mangoes', 'Fruits and Veggies'],
  ['Matcha Green Tea', 'Energy'],
  ['Metabolism Boost Enhancer', 'Energy'],
  ['Multivitamin Enhancer', 'Enhancers'],
  ['Muscle Builder Enhancer', 'Enhancers'],
  ['Orange Juice Blend', 'Fruits and Veggies'],
  ['Papaya Juice Blend', 'Fruits and Veggies'],
  ['Peanut Butter', 'Protein'],
  ['Pear Juice Blend', 'Fruits and Veggies'],
  ['Pear Passion Fruit Juice Blend', 'Fruits and Veggies'],
  ['Pineapples', 'Fruits and Veggies'],
  ['Probiotic Powder Enhancer', 'Enhancers'],
  ['Protein Blend', 'Protein'],
  ['Pumpkin', 'Fruits and Veggies'],
  ['Pure Recharge Enhancer', 'Enhancers'],
  ['Raspberries', 'Fruits and Veggies'],
  ['Spice Blend', 'Energy'],
  ['Spinach', 'Fruits and Veggies'],
  ['Strawberries', 'Fruits and Veggies'],
  ['Strawberries (sugar added)', 'Fruits and Veggies'],
  ['Sunwarrior Organic Plant-Based Protein', 'Protein'],
  ['Super Grains Enhancer', 'Enhancers'],
  ['Tart Cherries', 'Fruits and Veggies'],
  ['Whey Protein', 'Protein']
]);
</script>
<template>

</template>
<style scoped>

</style>